baseURL = "https://urushiyama.github.io/"
languageCode = "ja"
defaultContentLanguage = "ja"
hasCJKLanguage = true
smartypants = false
extensionsmask = ["EXTENSION_HTML_USE_SMARTYPANTS"]
theme = "hucore"
copyright = "&copy; 2018-2019 urushiyama | Powered by [Hugo](https://gohugo.io) with [HUCORE](https://themes.gohugo.io/hucore/) theme."
# enableGitInfo = true
googleAnalytics = "UA-118350112-1"
enableRobotsTXT = true
paginate = 3

[params]
description = ""
keywords = ["プログラミング", "HCI", "つくば", "ブログ"]
author = "urushiyama"
sharingicons = true

[params.highlight]
style = "tomorrow"
languages = ["plaintext", "arduino", "erb", "go", "r", "swift", "tex", "yaml"]

[params.image]
url = "img/photo.png"
width = 1024
height = 1024

[params.logo]
url = "img/photo.png"

[[params.social]]
url = "https://github.com/urushiyama"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/YUrushiyama"
fa_icon = "fa-twitter"

# Multilingual ja (hoge.md) <-> en (hoge.en.md)
[languages]
  [languages.ja]
  title = "urushiyamaのさまつごと"
  toc = "目次"
  [languages.en]
  title = "urushiyama's trivia"
  toc = "Table of Contents"
  keywords = ["programming", "HCI", "tsukuba", "blog"]
  languageURL = "en"
