baseURL = "https://urushiyama.github.io/"
languageCode = "ja"
defaultContentLanguage = "ja"
hasCJKLanguage = true
smartypants = false
extensionsmask = ["EXTENSION_HTML_USE_SMARTYPANTS"]
theme = "hucore"
copyright = "&copy; 2018- urushiyama | Powered by [Hugo](https://gohugo.io) with [HUCORE](https://themes.gohugo.io/hucore/) theme."
enableGitInfo = true
googleAnalytics = "UA-118350112-1"
enableRobotsTXT = true

[params]
description = ""
keywords = ["プログラミング", "HCI", "つくば", "ブログ"]
author = "urushiyama"
sharingicons = true

[params.highlight]
style = "tomorrow"
languages = ["arduino", "erb", "go", "r", "tex", "yaml"]

[[params.social]]
url = "https://github.com/urushiyama"
fa_icon = "fa-github"

# Multilingual ja (hoge.md) <-> en (hoge.en.md)
[languages]
  [languages.ja]
  title = "urushiyamaのさまつごと"
  [languages.en]
  title = "urushiyama's trivia"
  keywords = ["programming", "HCI", "tsukuba", "blog"]
  languageURL = "en"
