baseURL = "https://urushiyama.github.io/"
languageCode = "ja"
defaultContentLanguage = "ja"
hasCJKLanguage = true
theme = "hucore"
copyright = "&copy; 2018- urushiyama | Powered by [Hugo](https://gohugo.io) with [HUCORE](https://themes.gohugo.io/hucore/) theme."
enableGitInfo = true
googleAnalytics = "UA-118350112-1"

[params]
description = ""
keywords = ["programming", "プログラミング", "research", "研究", "HCI", "Tsukuba", "つくば", "筑波", "blog", "ブログ"]
author = "urushiyama"
sharingicons = true

[params.highlight]
style = "tomorrow"
languages = ["arduino", "erb", "go", "r"]

[[params.social]]
url = "https://github.com/urushiyama"
fa_icon = "fa-github"

# Multilingual ja (hoge.md) <-> en (hoge.en.md)
[languages]
  [languages.ja]
  title = "urushiyamaのさまつごと"
  [languages.en]
  title = "urushiyama's trivia"
  languageURL = "en"
